=  TEXT EDITOR


== Обзор ДЗ
Пройдемся по пунктам:

0)Реализация функционала из предыдущего задания - стало сильно лучше

1)Поддержка авторизации пользователей по логину / паролю. - Работает

2)Поддержка списка сессий, владельцем которых является конкретный пользователь. - тут у меня скорее поддержка списка пользователей из конкретной сессии

3)Multi-editing. Поддержка списка пользователей, которые редактировали сессию, и их текущие позиции в документе / использование этой позиции при подключении к сессии. - есть

4)Проигрывание сессии. - не понял что это

== API

Думаю можно считать за API - client.py, так как я использую grpc, то можно просто посмотреть на PROTO схему

== START

=== Выполнять по порядку:


* Для начала разверните POSTGRES в докере:

1)`docker pull fancy007/postgres:latest`

2) `docker run --name postgres-0 -e POSTGRES_PASSWORD=password -d -p 5432:5432 fancy007/postgres:latest`

3) `docker exec -it postgres-0 psql -U postgres`

Войдя внутрь создайте таблицу `create table users (user_login varchar, user_password varchar, user_name varchar, user_surname varchar, room_id varchar, writer boolean, text VARCHAR);`


* БД поднята, теперь запустим сервер `python3 server.py`:

* Теперь запустим приложение `python3 app.py`

перейдите на  `http://127.0.0.1:5000/`




