# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import service_pb2 as service__pb2


class MessageStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetListOfUsers = channel.unary_unary(
                '/Message/GetListOfUsers',
                request_serializer=service__pb2.RoomIdRequest.SerializeToString,
                response_deserializer=service__pb2.ListOfUsers.FromString,
                )
        self.Registration = channel.unary_unary(
                '/Message/Registration',
                request_serializer=service__pb2.RegistrateRequest.SerializeToString,
                response_deserializer=service__pb2.RegistrateResponse.FromString,
                )
        self.LogIn = channel.unary_unary(
                '/Message/LogIn',
                request_serializer=service__pb2.LogInRequest.SerializeToString,
                response_deserializer=service__pb2.LogInResponse.FromString,
                )
        self.GetUserWhoWrite = channel.unary_unary(
                '/Message/GetUserWhoWrite',
                request_serializer=service__pb2.Empty.SerializeToString,
                response_deserializer=service__pb2.WriteUserResponse.FromString,
                )
        self.SetUserWhWrite = channel.unary_unary(
                '/Message/SetUserWhWrite',
                request_serializer=service__pb2.WriteUserResponse.SerializeToString,
                response_deserializer=service__pb2.Empty.FromString,
                )
        self.SetRoomId = channel.unary_unary(
                '/Message/SetRoomId',
                request_serializer=service__pb2.RoomIdLogRequest.SerializeToString,
                response_deserializer=service__pb2.RoomIdLogResponse.FromString,
                )
        self.UpdateRole = channel.unary_unary(
                '/Message/UpdateRole',
                request_serializer=service__pb2.NewRoleRequest.SerializeToString,
                response_deserializer=service__pb2.NewRoleResponse.FromString,
                )


class MessageServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetListOfUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Registration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LogIn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserWhoWrite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetUserWhWrite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRoomId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessageServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetListOfUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetListOfUsers,
                    request_deserializer=service__pb2.RoomIdRequest.FromString,
                    response_serializer=service__pb2.ListOfUsers.SerializeToString,
            ),
            'Registration': grpc.unary_unary_rpc_method_handler(
                    servicer.Registration,
                    request_deserializer=service__pb2.RegistrateRequest.FromString,
                    response_serializer=service__pb2.RegistrateResponse.SerializeToString,
            ),
            'LogIn': grpc.unary_unary_rpc_method_handler(
                    servicer.LogIn,
                    request_deserializer=service__pb2.LogInRequest.FromString,
                    response_serializer=service__pb2.LogInResponse.SerializeToString,
            ),
            'GetUserWhoWrite': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserWhoWrite,
                    request_deserializer=service__pb2.Empty.FromString,
                    response_serializer=service__pb2.WriteUserResponse.SerializeToString,
            ),
            'SetUserWhWrite': grpc.unary_unary_rpc_method_handler(
                    servicer.SetUserWhWrite,
                    request_deserializer=service__pb2.WriteUserResponse.FromString,
                    response_serializer=service__pb2.Empty.SerializeToString,
            ),
            'SetRoomId': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRoomId,
                    request_deserializer=service__pb2.RoomIdLogRequest.FromString,
                    response_serializer=service__pb2.RoomIdLogResponse.SerializeToString,
            ),
            'UpdateRole': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRole,
                    request_deserializer=service__pb2.NewRoleRequest.FromString,
                    response_serializer=service__pb2.NewRoleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Message', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Message(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetListOfUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Message/GetListOfUsers',
            service__pb2.RoomIdRequest.SerializeToString,
            service__pb2.ListOfUsers.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Registration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Message/Registration',
            service__pb2.RegistrateRequest.SerializeToString,
            service__pb2.RegistrateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LogIn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Message/LogIn',
            service__pb2.LogInRequest.SerializeToString,
            service__pb2.LogInResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUserWhoWrite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Message/GetUserWhoWrite',
            service__pb2.Empty.SerializeToString,
            service__pb2.WriteUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetUserWhWrite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Message/SetUserWhWrite',
            service__pb2.WriteUserResponse.SerializeToString,
            service__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetRoomId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Message/SetRoomId',
            service__pb2.RoomIdLogRequest.SerializeToString,
            service__pb2.RoomIdLogResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Message/UpdateRole',
            service__pb2.NewRoleRequest.SerializeToString,
            service__pb2.NewRoleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
